version: '3.8'

services:
  video-processor:
    build: .
    volumes:
      - ./input:/input
    environment:
      - WATCH_DIR=/input
      - S3_ENDPOINT=http://minio:9000
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - minio

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  minio-data:
  redis-data: